import { supabase, json, fail, withAuth } from "./_supabase.js";

/* Putting feature rows back exactly as they were.

   Its own file rather than another branch in gis.js. A conditional
   `if (req.method === "POST" && ...)` sitting below an unconditional
   `if (req.method === "POST")` never runs, and fails silently with the
   wrong shape rather than an error — that has cost four sessions here.

   The whole point is the explicit Feature_ID. Connects is an array of
   feature ids, so a row that comes back under a new id is referenced by
   nothing and references nothing: undoing a delete would leave the
   drawing looking right and the network quietly severed. gis.js strips
   Feature_ID from its writable list deliberately, which is why this is
   separate rather than a flag on that one.

   Feature_ID is a bigserial, not an identity column, so an explicit
   value is accepted and the sequence needs no nudge afterwards — every
   id being restored was issued by that sequence already, so it is
   necessarily behind. */

const F = "Feature_ID,Project_ID,Layer_Key,Feature_Type,Geometry,Label,Attributes,Plot_ID,Feature_Role";
const W = new Set(F.split(","));
const pick = (o) => Object.fromEntries(Object.entries(o).filter(([k]) => W.has(k)));

export default withAuth(async function handler(req, context) {
  const db = supabase();
  const projectId = context?.params?.projectId;

  try {
    if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

    const { rows = [] } = await req.json();
    if (!rows.length) return json({ restored: 0, rows: [] });

    /* Project_ID is forced from the path rather than trusted from the
       body, so a stale journal entry cannot write a feature into a
       different project. */
    const payload = rows.map((r) => pick({ ...r, Project_ID: Number(projectId) }));

    const missing = payload.filter((r) => r.Feature_ID == null);
    if (missing.length) {
      return json({ error: "Every row must carry its original Feature_ID" }, 400);
    }

    /* Upsert rather than insert: undo of a delete finds the row gone and
       inserts it, undo of an edit finds it present and writes over it.
       One call either way, and re-running a restore is harmless. */
    const out = [];
    for (let i = 0; i < payload.length; i += 100) {
      const { data, error } = await db.from("GIS_Feature")
        .upsert(payload.slice(i, i + 100), { onConflict: "Feature_ID" })
        .select(F);
      if (error) throw error;
      out.push(...(data || []));
    }

    return json({ restored: out.length, rows: out });
  } catch (e) {
    /* An identity column rejects an explicit primary key with 428C9.
       Saying so plainly beats "restore failed", because the fix is a
       migration rather than anything the caller did. */
    if (e?.code === "428C9") {
      return fail({
        message: "Feature_ID cannot be set explicitly — the column is GENERATED ALWAYS. "
          + "Undo of a delete needs it altered to GENERATED BY DEFAULT.",
        code: e.code,
      }, 500);
    }
    return fail(e, 400);
  }
});

export const config = { path: "/api/projects/:projectId/gis-restore" };
