/* How a site reads in a picker.

   Pulled out of PortalAccountsAdmin so it can be asked questions
   directly: a screen's JSX cannot be imported by a check, and the
   fallback chain here is exactly the part worth asking about.

   ── Why it exists at all ──

   The picker read `Project_Name`, which is not a column. A read of a
   missing field is undefined, the `||` took over, and the dropdown
   showed site names and looked right — so nothing said the first term
   was dead until the endpoint SELECTED the same invented name and
   PostgREST refused the whole call, emptying both dropdowns on Portal
   Accounts.

   ── Reference and name, not one or the other ──

   Two schemes on neighbouring plots are routinely called the same
   thing, and what this field sets is a CEILING on what a contact may
   see. Picking the wrong one by guessing between two identical lines
   shows somebody another developer's site. So both, the way the rest of
   the app writes a project:

     2607.014 — Cedar Trees

   Display_Ref is generated by the database and is the reference printed
   on everything a developer has had from us. Project_Ref is the
   fallback for a project whose Display_Ref has not been generated yet. */

export function siteLabel(p = {}) {
  const ref = p.Display_Ref || p.Project_Ref;
  const site = p.Site_Name;
  if (ref && site) return `${ref} — ${site}`;
  /* Never nothing. An option with an empty label is a line somebody
     cannot tell from the line above it, and this picker decides what
     somebody outside the business is allowed to see. */
  return ref || site || `Project ${p.Project_ID}`;
}
