-- ════════════════════════════════════════════════════════════════
-- 0235 — OS tiles over a calibrated PDF, and the link to the grid
--
-- A project's background is a PDF from the developer, imported and
-- calibrated by hand: it knows its own scale and nothing about where
-- it sits on the National Grid. A bought Ordnance Survey tile knows
-- exactly where it sits. This is what lets the two be shown together,
-- aligned.
--
-- Two tables.
--
-- ── GIS_Overlay: the OS tile itself ──
--
-- Its LINEWORK, already read and already in grid metres, not the file
-- it came in. The DXF is read in the browser (osTile.js): units are
-- worked out from the numbers, the reseller's logo and scale bar are
-- set aside, and what is stored is polylines and text ready to draw.
-- No storage bucket and no re-reading on every open. A tile is small
-- — the one this was built against is 149 polylines — so it sits in
-- a jsonb column comfortably.
--
-- Several per project, because a site can need more than one tile
-- and because the developer's own DXF is the next thing to import the
-- same way. `Kind` says which.
--
-- ── GIS_Grid_Link: how the drawing sits on the grid ──
--
-- One per project. A similarity — rotation, uniform scale, position —
-- found from points matched between the PDF and the OS linework
-- (gridLink.js):
--
--     E = a·x \u2212 b·(\u2212y) + tx          x, y are drawing metres;
--     N = b·x + a·(\u2212y) + ty          the drawing's y runs south
--
-- The drawing never moves: the link places the OS tile over the
-- design, not the design under the tile. The matched points are kept
-- with it, so the fit can be looked at, added to or redone later
-- rather than taken on trust.
--
-- It supersedes GIS_Basemap's Ref_Easting / Ref_Northing, which tie
-- one point and assume the plan is drawn north-up. Those are left in
-- place and still read where no link exists.
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "GIS_Overlay" (
  "Overlay_ID"  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Project_ID"  bigint NOT NULL REFERENCES "Project" ("Project_ID") ON DELETE CASCADE,
  "Kind"        text   NOT NULL DEFAULT 'os_tile',
  "File_Name"   text,
  -- { polylines: [{ layer, pts: [[E, N], ...], closed }],
  --   texts:     [{ layer, at: [E, N], text, height, rotationDeg }] }
  "Linework"    jsonb  NOT NULL,
  -- Grid extent of the linework, for zooming to it and for finding
  -- which overlays a sheet or a view needs without reading them all.
  "Min_E"       double precision,
  "Min_N"       double precision,
  "Max_E"       double precision,
  "Max_N"       double precision,
  -- Layers switched off, the reseller's furniture to begin with.
  "Hidden_Layers" text[] NOT NULL DEFAULT '{}',
  "Visible"     boolean NOT NULL DEFAULT true,
  "Opacity"     double precision NOT NULL DEFAULT 0.8,
  "Created_At"  timestamptz NOT NULL DEFAULT now(),
  "Created_By"  text,
  CONSTRAINT gis_overlay_kind CHECK ("Kind" IN ('os_tile', 'cad'))
);

CREATE INDEX IF NOT EXISTS gis_overlay_project ON "GIS_Overlay" ("Project_ID");

CREATE TABLE IF NOT EXISTS "GIS_Grid_Link" (
  "Project_ID"  bigint PRIMARY KEY REFERENCES "Project" ("Project_ID") ON DELETE CASCADE,
  "A"           double precision NOT NULL,
  "B"           double precision NOT NULL,
  "TX"          double precision NOT NULL,
  "TY"          double precision NOT NULL,
  -- Reported, never applied twice: already inside A and B.
  "Scale"       double precision,
  "Rotation_Deg" double precision,
  "RMS_M"       double precision,
  -- [{ canvas: [x, y], grid: [E, N] }, ...] — the pairs it came from.
  "Points"      jsonb NOT NULL DEFAULT '[]',
  "Updated_At"  timestamptz NOT NULL DEFAULT now(),
  "Updated_By"  text
);

-- ── Checks ──────────────────────────────────────────────────────
--
--   SELECT "Overlay_ID", "Kind", "File_Name",
--          jsonb_array_length("Linework"->'polylines') AS polylines,
--          round("Min_E"), round("Min_N"), round("Max_E"), round("Max_N")
--     FROM "GIS_Overlay" WHERE "Project_ID" = <project>;
--
--   SELECT round("Scale"::numeric, 4), round("Rotation_Deg"::numeric, 2),
--          round("RMS_M"::numeric, 3), jsonb_array_length("Points")
--     FROM "GIS_Grid_Link" WHERE "Project_ID" = <project>;
