-- ════════════════════════════════════════════════════════════════
-- 0236 — the development's plot breakdown
--
-- A housebuilder names its house types: the Sunflower, a 3 bed
-- semi-detached, code SUNF; the Daisy, a 4 bed detached. This records
-- them for a development — name, code, type, and the floor plan — and
-- lets every plot entered say which one it is.
--
-- ── Per development, not per developer ──
--
-- The same builder reuses its names across sites, but not always its
-- specifications: a Sunflower on one scheme can be a different floor
-- plan, a different elevation or a different heat source on the next.
-- The breakdown is part of a project's own record, the way its plots
-- are. A developer-wide library that projects copy from is a later
-- step, and this table is shaped to be what it copies into.
--
-- ── What each column is ──
--
--   Name                the builder's name for it: Sunflower
--   Code                their short code: SUNF. Unique within a
--                       development, case aside, or a dropdown of codes
--                       could offer two SUNFs and mean different houses
--   Property_Config_ID  the house type as Aptus360 already knows it —
--                       bedrooms and form — so a plot given the code
--                       gets the type that drives its load
--   Storage_Path,
--   File_Name           the floor plan, in the private `house-types`
--                       bucket, opened by a signed link
--
-- Retired rather than deleted: plots point at these rows, and a plot
-- whose house type vanished would lose the name it was built as.
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "Project_House_Type" (
  "House_Type_ID"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Project_ID"         bigint NOT NULL REFERENCES "Project" ("Project_ID") ON DELETE CASCADE,
  "Name"               text   NOT NULL,
  "Code"               text,
  "Property_Config_ID" bigint REFERENCES "Property_Config" ("Property_Config_ID"),
  "Storage_Path"       text,
  "File_Name"          text,
  "Sort_Order"         integer NOT NULL DEFAULT 0,
  "Is_Active"          boolean NOT NULL DEFAULT true,
  "Created_At"         timestamptz NOT NULL DEFAULT now(),
  "Created_By"         text
);

CREATE INDEX IF NOT EXISTS project_house_type_project ON "Project_House_Type" ("Project_ID");

-- One SUNF per development, however it is capitalised, among the ones
-- in use. A retired one does not block its code being used again.
CREATE UNIQUE INDEX IF NOT EXISTS project_house_type_code
  ON "Project_House_Type" ("Project_ID", lower("Code"))
  WHERE "Code" IS NOT NULL AND "Is_Active";

-- ── The plot's link is NOT here any more — see 0237 ──
--
-- This added `Plot.House_Type_ID` with IF NOT EXISTS. On the live
-- database a column of that name already existed, referencing
-- "Property_Type" and holding values on 35 plots, so the line did
-- nothing and the breakdown wrote into the wrong column. Taken out so
-- a fresh database built from this folder matches the live one; the
-- link is `Plot.Project_House_Type_ID`, added and verified by 0237.

-- ── The floor plans' bucket ──
--
-- Private: a builder's floor plans are its commercial documents, and a
-- public link is a link that gets forwarded. Opened through a signed
-- link that lasts five minutes. Uploads go through a signed upload URL
-- minted by the server, so the bucket needs no storage policies.
--
-- Created here rather than by hand so the feature works the first time.
INSERT INTO storage.buckets (id, name, public)
VALUES ('house-types', 'house-types', false)
ON CONFLICT (id) DO NOTHING;

-- ── Checks ──────────────────────────────────────────────────────
--
--   SELECT "Name", "Code", "Property_Config_ID", "File_Name"
--     FROM "Project_House_Type" WHERE "Project_ID" = <project> AND "Is_Active"
--    ORDER BY "Sort_Order", "Name";
--
--   SELECT h."Code", COUNT(p."Plot_ID")
--     FROM "Project_House_Type" h
--     LEFT JOIN "Plot" p ON p."House_Type_ID" = h."House_Type_ID"
--    WHERE h."Project_ID" = <project>
--    GROUP BY h."Code";
